version: "3.9"

services:
  db-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-db-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: ${MONGODB_URI}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    networks:
      - penpal-network-staging

  auth-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-auth-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_SERVICE_URL: http://db-service:3001
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      - db-service
    networks:
      - penpal-network-staging

  ai-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-asimov-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3003
      DB_SERVICE_URL: http://db-service:3001/api/v1
      DB_SERVICE_API_KEY: ${DB_SERVICE_API_KEY}
    depends_on:
      - db-service
    networks:
      - penpal-network-staging

  payment-service:
    image: ghcr.io/${GHCR_OWNER}/payment-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3004
      AUTH_SERVICE_URL: http://auth-service:3002
      DB_SERVICE_URL: http://db-service:3001
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      DB_SERVICE_API_KEY: ${DB_SERVICE_API_KEY}
    depends_on:
      - auth-service
      - db-service
    networks:
      - penpal-network-staging

  monitoring-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-monitoring-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3005
      AUTH_SERVICE_URL: http://auth-service:3002
      DB_SERVICE_URL: http://db-service:3001
      AI_SERVICE_URL: http://ai-service:3003
    depends_on:
      - auth-service
      - db-service
      - ai-service
    networks:
      - penpal-network-staging

  notify-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-notify-service:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3006
      NOTIFY_SERVICE_API_KEY: ${NOTIFY_SERVICE_API_KEY}
    networks:
      - penpal-network-staging

  frontend:
    image: ghcr.io/${GHCR_OWNER}/penpal-frontend:develop-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - auth-service
      - payment-service
      - ai-service
      - monitoring-service
    networks:
      - penpal-network-staging

volumes:
  mongo-data-staging:

networks:
  penpal-network-staging:
    driver: bridge


