version: "3.9"

services:
  db-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-db-service:develop-latest
    restart: unless-stopped
    container_name: db-service
    env_file:
     - .env
    environment:
      NODE_ENV: development
      PORT: 3001
    networks:
      - penpal-staging-net

  auth-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-auth-service:develop-latest
    restart: unless-stopped
    container_name: auth-service
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3002
    depends_on:
      - db-service
    networks:
      - penpal-staging-net

  ai-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-asimov-service:develop-latest
    restart: unless-stopped
    container_name: asimov-service
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3003
    depends_on:
      - db-service
    networks:
      - penpal-staging-net

  payment-service:
    image: ghcr.io/${GHCR_OWNER}/payment-service:develop-latest
    restart: unless-stopped
    container_name: payment-service
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3004
    depends_on:
      - auth-service
      - db-service
    networks:
      - penpal-staging-net

  monitoring-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-monitoring-service:develop-latest
    restart: unless-stopped
    container_name: monitoring-service
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3005
    depends_on:
      - auth-service
      - db-service
      - ai-service
    networks:
      - penpal-staging-net

  notify-service:
    image: ghcr.io/${GHCR_OWNER}/penpal-ai-notify-service:develop-latest
    restart: unless-stopped
    container_name: notify-service
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3006
    networks:
      - penpal-staging-net

  frontend:
    image: ghcr.io/${GHCR_OWNER}/penpal-frontend:develop-latest
    restart: unless-stopped
    container_name: frontend
    env_file:
     - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - auth-service
      - payment-service
      - ai-service
      - monitoring-service
    networks:
      - penpal-staging-net

networks:
  penpal-staging-net:
    driver: bridge


